//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikasiSekolah.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jadwal
    {
        public int id { get; set; }
        public string Hari { get; set; }
        public string Jam_Mulai { get; set; }
        public string Jam_Selesai { get; set; }
        public int Mata_Pelajaran { get; set; }
        public int Guru { get; set; }
    }
}
